name: Blog CI/CD

on: [push, repository_dispatch]

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: 检查代码
      uses: actions/checkout@v2

    - name: 启动 node
      uses: actions/setup-node@v1
      with:
        # node-version: '12.x'
        node-version: '16.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: 安装环境依赖
      run: |
        npm install hexo-cli -g
        npm install yuque-hexo -g
        npm install
        yuque-hexo sync

    - name: 生成博客
      run: hexo generate

    - name: 部署博客
      run: |
        git clone "https://${{ secrets.GH_REF }}" deploy_git
        mv ./deploy_git/.git ./public
        cd ./public
        pwd
        tail -10 index.html
        git config user.name "walker"
        git config user.email "1853089362@163.com"
        git add .
        git commit -m "自动化构建  $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" origin:main